#!/usr/bin/env bash
# Path:     test/run_all_tests.sh
# Project:  systemd-evidence-collector
# Revision: 5
# Updated:  2026-09-26
# Purpose:  The single test entry point for this repository. CI runs exactly
#           this command, and so can you, from any directory:
#
#               bash test/run_all_tests.sh;
#
#           Exits 0 only when every suite below passed. Each suite reports
#           how many tests it executed, and a suite that executed none fails
#           the run, here and in CI alike. When TESTS_EXECUTED_FILE is set, as
#           CI sets it, each suite also appends "<label><TAB><count>" to that
#           file. Scratch output goes to one temporary directory, removed on
#           exit.
#
# Suites:
#           Fixture regeneration, then the collector shell suite.
#           unittest discovery over test/, counted from its own summary line.
#
# History:  Revisions 1 to 3 carried no header and are archived by sequence.
#           Revision 3 ran test/test_analyzer.py directly and reported no
#           counts. Revision 4 ran it through discovery, which is what the
#           README says CI does, and reported what each suite ran, but
#           declared itself Revision 2, which collides with sequence v2 in
#           archive/; it is archived as sequence v4. Revision 5 changes
#           this header and nothing else.
set -euo pipefail;

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)";
cd "${project_root}";
work_directory="$(mktemp -d "${TMPDIR:-/tmp}/revisualized_tests.XXXXXX")";
trap 'rm -rf -- "${work_directory}"' EXIT;

fail() {
  echo "FAIL: ${1}" >&2;
  exit 1;
};

# Refuses a count of zero or a count that is not a number. A suite that ran
# nothing has not passed.
record_tests_executed() {
  local label="${1}";
  local count="${2}";
  if ! [[ "${count}" =~ ^[0-9]+$ ]] || [ "${count}" -eq 0 ]; then
    fail "suite '${label}' reported '${count}' tests executed";
  fi;
  echo "  executed: ${label}: ${count}";
  if [ -n "${TESTS_EXECUTED_FILE:-}" ]; then
    printf '%s\t%s\n' "${label}" "${count}" >> "${TESTS_EXECUTED_FILE}";
  fi;
};

# The collector suite is a plain bash script of assertions that stops at the
# first failure, so it counts as one executed suite rather than a number of
# test cases.
run_collector_suite() {
  echo "== fixtures regenerated by the collector's own --fixture mode";
  bash test/generate_fixtures.sh;
  echo "== collector shell suite: bash test/test_collector.sh";
  bash test/test_collector.sh;
  record_tests_executed "collector shell suite (one script)" 1;
};

# The house runner. The count comes from unittest's own "Ran N tests" line.
# Python 3.12 and later also exit 5 when discovery finds nothing; 3.9 exits
# 0, which is why the count is checked rather than trusted.
run_unittest_suite() {
  local log_file="${work_directory}/unittest.log";
  local tests_ran;
  echo "== unittest: python3 -m unittest discover -s test -v ($(python3 --version 2>&1))";
  python3 -m unittest discover -s test -v 2>&1 | tee "${log_file}";
  tests_ran="$(sed -n 's/^Ran \([0-9][0-9]*\) tests\{0,1\} in .*/\1/p' "${log_file}" | tail -1)";
  record_tests_executed "unittest discover -s test" "${tests_ran:-0}";
};

run_collector_suite;
run_unittest_suite;

echo "All suites passed.";
